version: '3'

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/sendgrid-ingest:/code/sendgrid-ingest

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/sendgrid-ingest:/code/sendgrid-ingest

  ###############################################
  # This service's definition:
  ###############################################
  sendgrid-ingest:
    depends_on:
      - startup
    build:
      context: ./services-available/sendgrid-ingest
    container_name: sendgrid-ingest
    restart: always
    ports:
      - '${BIND:-0.0.0.0}:${PORT_PARSE:-8888}:8888'
    networks:
      - http_net
      - startup_net
      - arango_net
    volumes:
      - ./services-available/sendgrid-ingest:/code/sendgrid-ingest
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG
